name: Autograder

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
  workflow_dispatch:

jobs:
  grading:
    
    permissions:
      contents: write
      checks: write
     

    runs-on: ubuntu-latest

    services: 
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: policia_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    if: github.actor != 'github-classroom[bot]' && github.actor != 'WebTech-Journey-Autograder[bot]' && github.actor != 'ArthurCRodrigues'

    steps:
     
      - name: Generate AUTOGRADER-BOT App Token
        id: generate_app_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.AUTOGRADER_APP_ID }}
          private_key: ${{ secrets.AUTOGRADER_APP_PRIVATE_KEY }}
          repository: ${{ github.repository }} 

   
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: submission
          token: ${{ steps.generate_app_token.outputs.token }} 

      
      - name: Configure Git for AUTOGRADER-BOT
        run: |
          git config --global user.name "AUTOGRADER-BOT"
          git config --global user.email "AUTOGRADER-BOT[bot]@users.noreply.github.com"
          # Or a specific email associated with your bot, if you've configured one.

    
      - name: Check repository criteria
        uses: webtech-network/autograder@etapa-4
        with:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          autograder_bot_token: ${{ steps.generate_app_token.outputs.token }} 
          redis_name: ${{ secrets.REDIS_NAME }}
          redis_url: ${{ secrets.REDIS_URL }}
          autograder_engine: ${{ secrets.ENGINE }}

     
